const africa = [
    { id: 1, country_code: 'ZA', TZ_identifier: 'Africa/Johannesburg', country: 'South Africa', city: 'Johannesburg' },
    { id: 2, country_code: 'ZW', TZ_identifier: 'Africa/Harare', country: 'Zimbabwe', city: 'Harare' },
    { id: 3, country_code: 'ZM', TZ_identifier: 'Africa/Lusaka', country: 'Zambia', city: 'Lusaka' },
    { id: 4, country_code: 'CI', TZ_identifier: 'Africa/Abidjan', country: 'Ivory Coast', city: 'Abidjan' },
    { id: 5, country_code: 'DJ', TZ_identifier: 'Africa/Djibouti', country: 'Djibouti', city: 'Djibouti' },
    { id: 6, country_code: 'ER', TZ_identifier: 'Africa/Asmara', country: 'Eritrea', city: 'Asmara' },
    { id: 7, country_code: 'ET', TZ_identifier: 'Africa/Addis_Ababa', country: 'Ethiopia', city: 'Addis Ababa' },
    { id: 8, country_code: 'GH', TZ_identifier: 'Africa/Accra', country: 'Ghana', city: 'Accra' },
    { id: 9, country_code: 'GM', TZ_identifier: 'Africa/Banjul', country: 'Gambia', city: 'Banjul' },
    { id: 10, country_code: 'GN', TZ_identifier: 'Africa/Conakry', country: 'Guinea', city: 'Conakry' },
    { id: 11, country_code: 'GQ', TZ_identifier: 'Africa/Malabo', country: 'Equatorial Guinea', city: 'Malabo' },
    { id: 12, country_code: 'KE', TZ_identifier: 'Africa/Nairobi', country: 'Kenya', city: 'Nairobi' },
    { id: 13, country_code: 'LS', TZ_identifier: 'Africa/Maseru', country: 'Lesotho', city: 'Maseru' },
    { id: 14, country_code: 'LR', TZ_identifier: 'Africa/Monrovia', country: 'Liberia', city: 'Monrovia' },
    { id: 15, country_code: 'MA', TZ_identifier: 'Africa/Casablanca', country: 'Morocco', city: 'Casablanca' },
    { id: 16, country_code: 'ML', TZ_identifier: 'Africa/Bamako', country: 'Mali', city: 'Bamako' },
    { id: 17, country_code: 'MR', TZ_identifier: 'Africa/Nouakchott', country: 'Mauritania', city: 'Nouakchott' },
    { id: 18, country_code: 'MU', TZ_identifier: 'Indian/Mauritius', country: 'Mauritius', city: 'Port Louis' },
    { id: 19, country_code: 'MW', TZ_identifier: 'Africa/Blantyre', country: 'Malawi', city: 'Blantyre' },
    { id: 20, country_code: 'MZ', TZ_identifier: 'Africa/Maputo', country: 'Mozambique', city: 'Maputo' },
    { id: 21, country_code: 'NE', TZ_identifier: 'Africa/Niamey', country: 'Niger', city: 'Niamey' },
    { id: 22, country_code: 'NG', TZ_identifier: 'Africa/Lagos', country: 'Nigeria', city: 'Lagos' },
    { id: 23, country_code: 'SD', TZ_identifier: 'Africa/Khartoum', country: 'Sudan', city: 'Khartoum' },
    { id: 24, country_code: 'SN', TZ_identifier: 'Africa/Dakar', country: 'Senegal', city: 'Dakar' },
    { id: 25, country_code: 'SO', TZ_identifier: 'Africa/Mogadishu', country: 'Somalia', city: 'Mogadishu' },
    { id: 26, country_code: 'ST', TZ_identifier: 'Africa/Sao_Tome', country: 'Sao Tome and Principe', city: 'Sao Tome' },
    { id: 27, country_code: 'SS', TZ_identifier: 'Africa/Juba', country: 'South Sudan', city: 'Juba' },
    { id: 28, country_code: 'TD', TZ_identifier: 'Africa/Ndjamena', country: 'Chad', city: "N'Djamena" },
    { id: 29, country_code: 'TG', TZ_identifier: 'Africa/Lome', country: 'Togo', city: 'Lome' },
    { id: 30, country_code: 'TN', TZ_identifier: 'Africa/Tunis', country: 'Tunisia', city: 'Tunis' },
    { id: 31, country_code: 'UG', TZ_identifier: 'Africa/Kampala', country: 'Uganda', city: 'Kampala' },
    { id: 32, country_code: 'ZA', TZ_identifier: 'Africa/Johannesburg', country: 'South Africa', city: 'Johannesburg' },
    { id: 33, country_code: 'ZM', TZ_identifier: 'Africa/Lusaka', country: 'Zambia', city: 'Lusaka' },
    { id: 34, country_code: 'ZW', TZ_identifier: 'Africa/Harare', country: 'Zimbabwe', city: 'Harare' }
];

const america = [
    { id: 35, country_code: 'AR', TZ_identifier: 'America/Argentina/Buenos_Aires', country: 'Argentina', city: 'Buenos Aires' },
    { id: 36, country_code: 'BO', TZ_identifier: 'America/La_Paz', country: 'Bolivia', city: 'La Paz' },
    { id: 37, country_code: 'BR', TZ_identifier: 'America/Sao_Paulo', country: 'Brazil', city: 'Sao Paulo' },
    { id: 38, country_code: 'CA', TZ_identifier: 'America/Toronto', country: 'Canada', city: 'Toronto' },
    { id: 39, country_code: 'CL', TZ_identifier: 'America/Santiago', country: 'Chile', city: 'Santiago' },
    { id: 40, country_code: 'CO', TZ_identifier: 'America/Bogota', country: 'Colombia', city: 'Bogota' },
    { id: 41, country_code: 'CR', TZ_identifier: 'America/Costa_Rica', country: 'Costa Rica', city: 'San Jose' },
    { id: 42, country_code: 'CU', TZ_identifier: 'America/Havana', country: 'Cuba', city: 'Havana' },
    { id: 43, country_code: 'DO', TZ_identifier: 'America/Santo_Domingo', country: 'Dominican Republic', city: 'Santo Domingo' },
    { id: 44, country_code: 'EC', TZ_identifier: 'America/Guayaquil', country: 'Ecuador', city: 'Guayaquil' },
    { id: 45, country_code: 'SR', TZ_identifier: 'America/Paramaribo', country: 'Suriname', city: 'Paramaribo' },
    { id: 46, country_code: 'TT', TZ_identifier: 'America/Port_of_Spain', country: 'Trinidad and Tobago', city: 'Port of Spain' },
    { id: 47, country_code: 'US', TZ_identifier: 'America/New_York', country: 'United States', city: 'New York' },
    { id: 48, country_code: 'UY', TZ_identifier: 'America/Montevideo', country: 'Uruguay', city: 'Montevideo' },
    { id: 49, country_code: 'VE', TZ_identifier: 'America/Caracas', country: 'Venezuela', city: 'Caracas' }
];

const asia = [
    { id: 50, country_code: 'AF', TZ_identifier: 'Asia/Kabul', country: 'Afghanistan', city: 'Kabul' },
    { id: 51, country_code: 'AM', TZ_identifier: 'Asia/Yerevan', country: 'Armenia', city: 'Yerevan' },
    { id: 52, country_code: 'AZ', TZ_identifier: 'Asia/Baku', country: 'Azerbaijan', city: 'Baku' },
    { id: 53, country_code: 'BH', TZ_identifier: 'Asia/Bahrain', country: 'Bahrain', city: 'Manama' },
    { id: 54, country_code: 'BD', TZ_identifier: 'Asia/Dhaka', country: 'Bangladesh', city: 'Dhaka' },
    { id: 55, country_code: 'BT', TZ_identifier: 'Asia/Thimphu', country: 'Bhutan', city: 'Thimphu' },
    { id: 56, country_code: 'CN', TZ_identifier: 'Asia/Shanghai', country: 'China', city: 'Shanghai' },
    { id: 57, country_code: 'CY', TZ_identifier: 'Asia/Nicosia', country: 'Cyprus', city: 'Nicosia' },
    { id: 58, country_code: 'GE', TZ_identifier: 'Asia/Tbilisi', country: 'Georgia', city: 'Tbilisi' },
    { id: 59, country_code: 'IN', TZ_identifier: 'Asia/Kolkata', country: 'India', city: 'Kolkata' },
    { id: 60, country_code: 'ID', TZ_identifier: 'Asia/Jakarta', country: 'Indonesia', city: 'Jakarta' },
    { id: 61, country_code: 'IR', TZ_identifier: 'Asia/Tehran', country: 'Iran', city: 'Tehran' },
    { id: 62, country_code: 'IQ', TZ_identifier: 'Asia/Baghdad', country: 'Iraq', city: 'Baghdad' },
    { id: 63, country_code: 'IL', TZ_identifier: 'Asia/Jerusalem', country: 'Israel', city: 'Jerusalem' },
    { id: 64, country_code: 'JP', TZ_identifier: 'Asia/Tokyo', country: 'Japan', city: 'Tokyo' },
    { id: 65, country_code: 'JO', TZ_identifier: 'Asia/Amman', country: 'Jordan', city: 'Amman' },
    { id: 66, country_code: 'KZ', TZ_identifier: 'Asia/Almaty', country: 'Kazakhstan', city: 'Almaty' },
    { id: 67, country_code: 'KW', TZ_identifier: 'Asia/Kuwait', country: 'Kuwait', city: 'Kuwait City' },
    { id: 68, country_code: 'LA', TZ_identifier: 'Asia/Vientiane', country: 'Laos', city: 'Vientiane' },
    { id: 69, country_code: 'LB', TZ_identifier: 'Asia/Beirut', country: 'Lebanon', city: 'Beirut' },
    { id: 70, country_code: 'MY', TZ_identifier: 'Asia/Kuala_Lumpur', country: 'Malaysia', city: 'Kuala Lumpur' },
    { id: 71, country_code: 'MM', TZ_identifier: 'Asia/Yangon', country: 'Myanmar', city: 'Yangon' },
    { id: 72, country_code: 'MN', TZ_identifier: 'Asia/Ulaanbaatar', country: 'Mongolia', city: 'Ulaanbaatar' },
    { id: 73, country_code: 'NP', TZ_identifier: 'Asia/Kathmandu', country: 'Nepal', city: 'Kathmandu' },
    { id: 74, country_code: 'OM', TZ_identifier: 'Asia/Muscat', country: 'Oman', city: 'Muscat' },
    { id: 75, country_code: 'PK', TZ_identifier: 'Asia/Karachi', country: 'Pakistan', city: 'Karachi' },
    { id: 76, country_code: 'PH', TZ_identifier: 'Asia/Manila', country: 'Philippines', city: 'Manila' },
    { id: 77, country_code: 'QA', TZ_identifier: 'Asia/Qatar', country: 'Qatar', city: 'Doha' },
    { id: 78, country_code: 'SA', TZ_identifier: 'Asia/Riyadh', country: 'Saudi Arabia', city: 'Riyadh' },
    { id: 79, country_code: 'SG', TZ_identifier: 'Asia/Singapore', country: 'Singapore', city: 'Singapore' },
    { id: 80, country_code: 'KR', TZ_identifier: 'Asia/Seoul', country: 'South Korea', city: 'Seoul' },
    { id: 81, country_code: 'LK', TZ_identifier: 'Asia/Colombo', country: 'Sri Lanka', city: 'Colombo' },
    { id: 82, country_code: 'SY', TZ_identifier: 'Asia/Damascus', country: 'Syria', city: 'Damascus' },
    { id: 83, country_code: 'TJ', TZ_identifier: 'Asia/Dushanbe', country: 'Tajikistan', city: 'Dushanbe' },
    { id: 84, country_code: 'TH', TZ_identifier: 'Asia/Bangkok', country: 'Thailand', city: 'Bangkok' },
    { id: 85, country_code: 'TR', TZ_identifier: 'Asia/Istanbul', country: 'Turkey', city: 'Istanbul' },
    { id: 86, country_code: 'TM', TZ_identifier: 'Asia/Ashgabat', country: 'Turkmenistan', city: 'Ashgabat' },
    { id: 87, country_code: 'AE', TZ_identifier: 'Asia/Dubai', country: 'United Arab Emirates', city: 'Dubai' },
    { id: 88, country_code: 'UZ', TZ_identifier: 'Asia/Tashkent', country: 'Uzbekistan', city: 'Tashkent' },
    { id: 89, country_code: 'VN', TZ_identifier: 'Asia/Ho_Chi_Minh', country: 'Vietnam', city: 'Ho Chi Minh City' }
];

const europe = [
    { id: 90, country_code: 'AL', TZ_identifier: 'Europe/Tirane', country: 'Albania', city: 'Tirane' },
    { id: 91, country_code: 'AD', TZ_identifier: 'Europe/Andorra', country: 'Andorra', city: 'Andorra la Vella' },
    { id: 92, country_code: 'AT', TZ_identifier: 'Europe/Vienna', country: 'Austria', city: 'Vienna' },
    { id: 93, country_code: 'BY', TZ_identifier: 'Europe/Minsk', country: 'Belarus', city: 'Minsk' },
    { id: 94, country_code: 'BE', TZ_identifier: 'Europe/Brussels', country: 'Belgium', city: 'Brussels' },
    { id: 95, country_code: 'BA', TZ_identifier: 'Europe/Sarajevo', country: 'Bosnia and Herzegovina', city: 'Sarajevo' },
    { id: 96, country_code: 'BG', TZ_identifier: 'Europe/Sofia', country: 'Bulgaria', city: 'Sofia' },
    { id: 97, country_code: 'HR', TZ_identifier: 'Europe/Zagreb', country: 'Croatia', city: 'Zagreb' },
    { id: 98, country_code: 'CY', TZ_identifier: 'Asia/Nicosia', country: 'Cyprus', city: 'Nicosia' },
    { id: 99, country_code: 'CZ', TZ_identifier: 'Europe/Prague', country: 'Czech Republic', city: 'Prague' },
    { id: 100, country_code: 'DK', TZ_identifier: 'Europe/Copenhagen', country: 'Denmark', city: 'Copenhagen' },
    { id: 101, country_code: 'EE', TZ_identifier: 'Europe/Tallinn', country: 'Estonia', city: 'Tallinn' },
    { id: 102, country_code: 'FI', TZ_identifier: 'Europe/Helsinki', country: 'Finland', city: 'Helsinki' },
    { id: 103, country_code: 'FR', TZ_identifier: 'Europe/Paris', country: 'France', city: 'Paris' },
    { id: 104, country_code: 'DE', TZ_identifier: 'Europe/Berlin', country: 'Germany', city: 'Berlin' },
    { id: 105, country_code: 'GR', TZ_identifier: 'Europe/Athens', country: 'Greece', city: 'Athens' },
    { id: 106, country_code: 'HU', TZ_identifier: 'Europe/Budapest', country: 'Hungary', city: 'Budapest' },
    { id: 107, country_code: 'IS', TZ_identifier: 'Atlantic/Reykjavik', country: 'Iceland', city: 'Reykjavik' },
    { id: 108, country_code: 'IE', TZ_identifier: 'Europe/Dublin', country: 'Ireland', city: 'Dublin' },
    { id: 109, country_code: 'IT', TZ_identifier: 'Europe/Rome', country: 'Italy', city: 'Rome' },
    { id: 110, country_code: 'LI', TZ_identifier: 'Europe/Vaduz', country: 'Liechtenstein', city: 'Vaduz' },
    { id: 111, country_code: 'LT', TZ_identifier: 'Europe/Vilnius', country: 'Lithuania', city: 'Vilnius' },
    { id: 112, country_code: 'LU', TZ_identifier: 'Europe/Luxembourg', country: 'Luxembourg', city: 'Luxembourg City' },
    { id: 113, country_code: 'MT', TZ_identifier: 'Europe/Malta', country: 'Malta', city: 'Valletta' },
    { id: 114, country_code: 'MD', TZ_identifier: 'Europe/Chisinau', country: 'Moldova', city: 'Chisinau' },
    { id: 115, country_code: 'MC', TZ_identifier: 'Europe/Monaco', country: 'Monaco', city: 'Monaco' },
    { id: 116, country_code: 'ME', TZ_identifier: 'Europe/Podgorica', country: 'Montenegro', city: 'Podgorica' },
    { id: 117, country_code: 'NL', TZ_identifier: 'Europe/Amsterdam', country: 'Netherlands', city: 'Amsterdam' },
    { id: 118, country_code: 'MK', TZ_identifier: 'Europe/Skopje', country: 'North Macedonia', city: 'Skopje' },
    { id: 119, country_code: 'NO', TZ_identifier: 'Europe/Oslo', country: 'Norway', city: 'Oslo' },
    { id: 120, country_code: 'PL', TZ_identifier: 'Europe/Warsaw', country: 'Poland', city: 'Warsaw' },
    { id: 121, country_code: 'PT', TZ_identifier: 'Europe/Lisbon', country: 'Portugal', city: 'Lisbon' },
    { id: 122, country_code: 'RO', TZ_identifier: 'Europe/Bucharest', country: 'Romania', city: 'Bucharest' },
    { id: 123, country_code: 'RU', TZ_identifier: 'Europe/Moscow', country: 'Russia', city: 'Moscow' },
    { id: 124, country_code: 'SM', TZ_identifier: 'Europe/San_Marino', country: 'San Marino', city: 'San Marino' },
    { id: 125, country_code: 'RS', TZ_identifier: 'Europe/Belgrade', country: 'Serbia', city: 'Belgrade' },
    { id: 126, country_code: 'SK', TZ_identifier: 'Europe/Bratislava', country: 'Slovakia', city: 'Bratislava' },
    { id: 127, country_code: 'SI', TZ_identifier: 'Europe/Ljubljana', country: 'Slovenia', city: 'Ljubljana' },
    { id: 128, country_code: 'ES', TZ_identifier: 'Europe/Madrid', country: 'Spain', city: 'Madrid' },
    { id: 129, country_code: 'SE', TZ_identifier: 'Europe/Stockholm', country: 'Sweden', city: 'Stockholm' },
    { id: 130, country_code: 'CH', TZ_identifier: 'Europe/Zurich', country: 'Switzerland', city: 'Zurich' },
    { id: 131, country_code: 'UA', TZ_identifier: 'Europe/Kiev', country: 'Ukraine', city: 'Kiev' },
    { id: 132, country_code: 'GB', TZ_identifier: 'Europe/London', country: 'United Kingdom', city: 'London' },
    { id: 133, country_code: 'VA', TZ_identifier: 'Europe/Vatican', country: 'Vatican City', city: 'Vatican City' }
];

const oceania = [
    { id: 134, country_code: 'AU', TZ_identifier: 'Australia/Sydney', country: 'Australia', city: 'Sydney' },
    { id: 135, country_code: 'FJ', TZ_identifier: 'Pacific/Fiji', country: 'Fiji', city: 'Suva' },
    { id: 136, country_code: 'KI', TZ_identifier: 'Pacific/Tarawa', country: 'Kiribati', city: 'Tarawa' },
    { id: 137, country_code: 'MH', TZ_identifier: 'Pacific/Majuro', country: 'Marshall Islands', city: 'Majuro' },
    { id: 138, country_code: 'NR', TZ_identifier: 'Pacific/Nauru', country: 'Nauru', city: 'Yaren' },
    { id: 139, country_code: 'NZ', TZ_identifier: 'Pacific/Auckland', country: 'New Zealand', city: 'Auckland' },
    { id: 140, country_code: 'PW', TZ_identifier: 'Pacific/Palau', country: 'Palau', city: 'Ngerulmud' },
    { id: 141, country_code: 'PG', TZ_identifier: 'Pacific/Port_Moresby', country: 'Papua New Guinea', city: 'Port Moresby' },
    { id: 142, country_code: 'WS', TZ_identifier: 'Pacific/Apia', country: 'Samoa', city: 'Apia' },
    { id: 143, country_code: 'SB', TZ_identifier: 'Pacific/Guadalcanal', country: 'Solomon Islands', city: 'Honiara' },
    { id: 144, country_code: 'TO', TZ_identifier: 'Pacific/Tongatapu', country: 'Tonga', city: 'Nuku\'alofa' },
    { id: 145, country_code: 'TV', TZ_identifier: 'Pacific/Funafuti', country: 'Tuvalu', city: 'Funafuti' },
    { id: 146, country_code: 'VU', TZ_identifier: 'Pacific/Efate', country: 'Vanuatu', city: 'Port Vila' }, 
];

 
const countrys = [...africa, ...asia, ...america, ...europe, ...oceania];


export default countrys